//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace CareLib.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class CareForYouEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new CareForYouEntities object using the connection string found in the 'CareForYouEntities' section of the application configuration file.
        /// </summary>
        public CareForYouEntities() : base("name=CareForYouEntities", "CareForYouEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CareForYouEntities object.
        /// </summary>
        public CareForYouEntities(string connectionString) : base(connectionString, "CareForYouEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CareForYouEntities object.
        /// </summary>
        public CareForYouEntities(EntityConnection connection) : base(connection, "CareForYouEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CareCodeDefination> CareCodeDefinations
        {
            get
            {
                if ((_CareCodeDefinations == null))
                {
                    _CareCodeDefinations = base.CreateObjectSet<CareCodeDefination>("CareCodeDefinations");
                }
                return _CareCodeDefinations;
            }
        }
        private ObjectSet<CareCodeDefination> _CareCodeDefinations;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CareCode> CareCodes
        {
            get
            {
                if ((_CareCodes == null))
                {
                    _CareCodes = base.CreateObjectSet<CareCode>("CareCodes");
                }
                return _CareCodes;
            }
        }
        private ObjectSet<CareCode> _CareCodes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<DoctorDetail> DoctorDetails
        {
            get
            {
                if ((_DoctorDetails == null))
                {
                    _DoctorDetails = base.CreateObjectSet<DoctorDetail>("DoctorDetails");
                }
                return _DoctorDetails;
            }
        }
        private ObjectSet<DoctorDetail> _DoctorDetails;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<doctor> doctors
        {
            get
            {
                if ((_doctors == null))
                {
                    _doctors = base.CreateObjectSet<doctor>("doctors");
                }
                return _doctors;
            }
        }
        private ObjectSet<doctor> _doctors;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<HomeContent> HomeContents
        {
            get
            {
                if ((_HomeContents == null))
                {
                    _HomeContents = base.CreateObjectSet<HomeContent>("HomeContents");
                }
                return _HomeContents;
            }
        }
        private ObjectSet<HomeContent> _HomeContents;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CompanyDetail> CompanyDetails
        {
            get
            {
                if ((_CompanyDetails == null))
                {
                    _CompanyDetails = base.CreateObjectSet<CompanyDetail>("CompanyDetails");
                }
                return _CompanyDetails;
            }
        }
        private ObjectSet<CompanyDetail> _CompanyDetails;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CareCodeDefinations EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCareCodeDefinations(CareCodeDefination careCodeDefination)
        {
            base.AddObject("CareCodeDefinations", careCodeDefination);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CareCodes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCareCodes(CareCode careCode)
        {
            base.AddObject("CareCodes", careCode);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the DoctorDetails EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDoctorDetails(DoctorDetail doctorDetail)
        {
            base.AddObject("DoctorDetails", doctorDetail);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the doctors EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTodoctors(doctor doctor)
        {
            base.AddObject("doctors", doctor);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the HomeContents EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToHomeContents(HomeContent homeContent)
        {
            base.AddObject("HomeContents", homeContent);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CompanyDetails EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCompanyDetails(CompanyDetail companyDetail)
        {
            base.AddObject("CompanyDetails", companyDetail);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CareForYouModel", Name="CareCode")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CareCode : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CareCode object.
        /// </summary>
        /// <param name="codeid">Initial value of the codeid property.</param>
        public static CareCode CreateCareCode(global::System.Int32 codeid)
        {
            CareCode careCode = new CareCode();
            careCode.codeid = codeid;
            return careCode;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 codeid
        {
            get
            {
                return _codeid;
            }
            set
            {
                if (_codeid != value)
                {
                    OncodeidChanging(value);
                    ReportPropertyChanging("codeid");
                    _codeid = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("codeid");
                    OncodeidChanged();
                }
            }
        }
        private global::System.Int32 _codeid;
        partial void OncodeidChanging(global::System.Int32 value);
        partial void OncodeidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String codedesc
        {
            get
            {
                return _codedesc;
            }
            set
            {
                OncodedescChanging(value);
                ReportPropertyChanging("codedesc");
                _codedesc = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("codedesc");
                OncodedescChanged();
            }
        }
        private global::System.String _codedesc;
        partial void OncodedescChanging(global::System.String value);
        partial void OncodedescChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IsDeleted
        {
            get
            {
                return _IsDeleted;
            }
            set
            {
                OnIsDeletedChanging(value);
                ReportPropertyChanging("IsDeleted");
                _IsDeleted = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsDeleted");
                OnIsDeletedChanged();
            }
        }
        private Nullable<global::System.Int32> _IsDeleted;
        partial void OnIsDeletedChanging(Nullable<global::System.Int32> value);
        partial void OnIsDeletedChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CareForYouModel", Name="CareCodeDefination")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CareCodeDefination : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CareCodeDefination object.
        /// </summary>
        /// <param name="codeDefinationsid">Initial value of the CodeDefinationsid property.</param>
        public static CareCodeDefination CreateCareCodeDefination(global::System.Int32 codeDefinationsid)
        {
            CareCodeDefination careCodeDefination = new CareCodeDefination();
            careCodeDefination.CodeDefinationsid = codeDefinationsid;
            return careCodeDefination;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CodeDefinationsid
        {
            get
            {
                return _CodeDefinationsid;
            }
            set
            {
                if (_CodeDefinationsid != value)
                {
                    OnCodeDefinationsidChanging(value);
                    ReportPropertyChanging("CodeDefinationsid");
                    _CodeDefinationsid = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CodeDefinationsid");
                    OnCodeDefinationsidChanged();
                }
            }
        }
        private global::System.Int32 _CodeDefinationsid;
        partial void OnCodeDefinationsidChanging(global::System.Int32 value);
        partial void OnCodeDefinationsidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> codeid
        {
            get
            {
                return _codeid;
            }
            set
            {
                OncodeidChanging(value);
                ReportPropertyChanging("codeid");
                _codeid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("codeid");
                OncodeidChanged();
            }
        }
        private Nullable<global::System.Int32> _codeid;
        partial void OncodeidChanging(Nullable<global::System.Int32> value);
        partial void OncodeidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String codeDescriptions
        {
            get
            {
                return _codeDescriptions;
            }
            set
            {
                OncodeDescriptionsChanging(value);
                ReportPropertyChanging("codeDescriptions");
                _codeDescriptions = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("codeDescriptions");
                OncodeDescriptionsChanged();
            }
        }
        private global::System.String _codeDescriptions;
        partial void OncodeDescriptionsChanging(global::System.String value);
        partial void OncodeDescriptionsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String codeDetails
        {
            get
            {
                return _codeDetails;
            }
            set
            {
                OncodeDetailsChanging(value);
                ReportPropertyChanging("codeDetails");
                _codeDetails = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("codeDetails");
                OncodeDetailsChanged();
            }
        }
        private global::System.String _codeDetails;
        partial void OncodeDetailsChanging(global::System.String value);
        partial void OncodeDetailsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IsDeleted
        {
            get
            {
                return _IsDeleted;
            }
            set
            {
                OnIsDeletedChanging(value);
                ReportPropertyChanging("IsDeleted");
                _IsDeleted = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsDeleted");
                OnIsDeletedChanged();
            }
        }
        private Nullable<global::System.Int32> _IsDeleted;
        partial void OnIsDeletedChanging(Nullable<global::System.Int32> value);
        partial void OnIsDeletedChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CareForYouModel", Name="CompanyDetail")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CompanyDetail : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CompanyDetail object.
        /// </summary>
        /// <param name="companyid">Initial value of the companyid property.</param>
        public static CompanyDetail CreateCompanyDetail(global::System.Int32 companyid)
        {
            CompanyDetail companyDetail = new CompanyDetail();
            companyDetail.companyid = companyid;
            return companyDetail;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 companyid
        {
            get
            {
                return _companyid;
            }
            set
            {
                if (_companyid != value)
                {
                    OncompanyidChanging(value);
                    ReportPropertyChanging("companyid");
                    _companyid = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("companyid");
                    OncompanyidChanged();
                }
            }
        }
        private global::System.Int32 _companyid;
        partial void OncompanyidChanging(global::System.Int32 value);
        partial void OncompanyidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CompanyTitle
        {
            get
            {
                return _CompanyTitle;
            }
            set
            {
                OnCompanyTitleChanging(value);
                ReportPropertyChanging("CompanyTitle");
                _CompanyTitle = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CompanyTitle");
                OnCompanyTitleChanged();
            }
        }
        private global::System.String _CompanyTitle;
        partial void OnCompanyTitleChanging(global::System.String value);
        partial void OnCompanyTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CompanyName
        {
            get
            {
                return _CompanyName;
            }
            set
            {
                OnCompanyNameChanging(value);
                ReportPropertyChanging("CompanyName");
                _CompanyName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CompanyName");
                OnCompanyNameChanged();
            }
        }
        private global::System.String _CompanyName;
        partial void OnCompanyNameChanging(global::System.String value);
        partial void OnCompanyNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CompanyAddress
        {
            get
            {
                return _CompanyAddress;
            }
            set
            {
                OnCompanyAddressChanging(value);
                ReportPropertyChanging("CompanyAddress");
                _CompanyAddress = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CompanyAddress");
                OnCompanyAddressChanged();
            }
        }
        private global::System.String _CompanyAddress;
        partial void OnCompanyAddressChanging(global::System.String value);
        partial void OnCompanyAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CompanyAddress2
        {
            get
            {
                return _CompanyAddress2;
            }
            set
            {
                OnCompanyAddress2Changing(value);
                ReportPropertyChanging("CompanyAddress2");
                _CompanyAddress2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CompanyAddress2");
                OnCompanyAddress2Changed();
            }
        }
        private global::System.String _CompanyAddress2;
        partial void OnCompanyAddress2Changing(global::System.String value);
        partial void OnCompanyAddress2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CompanyState
        {
            get
            {
                return _CompanyState;
            }
            set
            {
                OnCompanyStateChanging(value);
                ReportPropertyChanging("CompanyState");
                _CompanyState = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CompanyState");
                OnCompanyStateChanged();
            }
        }
        private global::System.String _CompanyState;
        partial void OnCompanyStateChanging(global::System.String value);
        partial void OnCompanyStateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CompanyCountry
        {
            get
            {
                return _CompanyCountry;
            }
            set
            {
                OnCompanyCountryChanging(value);
                ReportPropertyChanging("CompanyCountry");
                _CompanyCountry = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CompanyCountry");
                OnCompanyCountryChanged();
            }
        }
        private global::System.String _CompanyCountry;
        partial void OnCompanyCountryChanging(global::System.String value);
        partial void OnCompanyCountryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CompanyZipCode
        {
            get
            {
                return _CompanyZipCode;
            }
            set
            {
                OnCompanyZipCodeChanging(value);
                ReportPropertyChanging("CompanyZipCode");
                _CompanyZipCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CompanyZipCode");
                OnCompanyZipCodeChanged();
            }
        }
        private global::System.String _CompanyZipCode;
        partial void OnCompanyZipCodeChanging(global::System.String value);
        partial void OnCompanyZipCodeChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CareForYouModel", Name="doctor")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class doctor : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new doctor object.
        /// </summary>
        /// <param name="docid">Initial value of the docid property.</param>
        public static doctor Createdoctor(global::System.Int32 docid)
        {
            doctor doctor = new doctor();
            doctor.docid = docid;
            return doctor;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 docid
        {
            get
            {
                return _docid;
            }
            set
            {
                if (_docid != value)
                {
                    OndocidChanging(value);
                    ReportPropertyChanging("docid");
                    _docid = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("docid");
                    OndocidChanged();
                }
            }
        }
        private global::System.Int32 _docid;
        partial void OndocidChanging(global::System.Int32 value);
        partial void OndocidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DoctorName
        {
            get
            {
                return _DoctorName;
            }
            set
            {
                OnDoctorNameChanging(value);
                ReportPropertyChanging("DoctorName");
                _DoctorName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DoctorName");
                OnDoctorNameChanged();
            }
        }
        private global::System.String _DoctorName;
        partial void OnDoctorNameChanging(global::System.String value);
        partial void OnDoctorNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DoctorMiddleName
        {
            get
            {
                return _DoctorMiddleName;
            }
            set
            {
                OnDoctorMiddleNameChanging(value);
                ReportPropertyChanging("DoctorMiddleName");
                _DoctorMiddleName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DoctorMiddleName");
                OnDoctorMiddleNameChanged();
            }
        }
        private global::System.String _DoctorMiddleName;
        partial void OnDoctorMiddleNameChanging(global::System.String value);
        partial void OnDoctorMiddleNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DoctorLastName
        {
            get
            {
                return _DoctorLastName;
            }
            set
            {
                OnDoctorLastNameChanging(value);
                ReportPropertyChanging("DoctorLastName");
                _DoctorLastName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DoctorLastName");
                OnDoctorLastNameChanged();
            }
        }
        private global::System.String _DoctorLastName;
        partial void OnDoctorLastNameChanging(global::System.String value);
        partial void OnDoctorLastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Dob
        {
            get
            {
                return _Dob;
            }
            set
            {
                OnDobChanging(value);
                ReportPropertyChanging("Dob");
                _Dob = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Dob");
                OnDobChanged();
            }
        }
        private Nullable<global::System.DateTime> _Dob;
        partial void OnDobChanging(Nullable<global::System.DateTime> value);
        partial void OnDobChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String sex
        {
            get
            {
                return _sex;
            }
            set
            {
                OnsexChanging(value);
                ReportPropertyChanging("sex");
                _sex = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("sex");
                OnsexChanged();
            }
        }
        private global::System.String _sex;
        partial void OnsexChanging(global::System.String value);
        partial void OnsexChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DocPhoto
        {
            get
            {
                return _DocPhoto;
            }
            set
            {
                OnDocPhotoChanging(value);
                ReportPropertyChanging("DocPhoto");
                _DocPhoto = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DocPhoto");
                OnDocPhotoChanged();
            }
        }
        private global::System.String _DocPhoto;
        partial void OnDocPhotoChanging(global::System.String value);
        partial void OnDocPhotoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DocEmail
        {
            get
            {
                return _DocEmail;
            }
            set
            {
                OnDocEmailChanging(value);
                ReportPropertyChanging("DocEmail");
                _DocEmail = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DocEmail");
                OnDocEmailChanged();
            }
        }
        private global::System.String _DocEmail;
        partial void OnDocEmailChanging(global::System.String value);
        partial void OnDocEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IsDeleted
        {
            get
            {
                return _IsDeleted;
            }
            set
            {
                OnIsDeletedChanging(value);
                ReportPropertyChanging("IsDeleted");
                _IsDeleted = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsDeleted");
                OnIsDeletedChanged();
            }
        }
        private Nullable<global::System.Int32> _IsDeleted;
        partial void OnIsDeletedChanging(Nullable<global::System.Int32> value);
        partial void OnIsDeletedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CreatedDate
        {
            get
            {
                return _CreatedDate;
            }
            set
            {
                OnCreatedDateChanging(value);
                ReportPropertyChanging("CreatedDate");
                _CreatedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatedDate");
                OnCreatedDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _CreatedDate;
        partial void OnCreatedDateChanging(Nullable<global::System.DateTime> value);
        partial void OnCreatedDateChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CareForYouModel", Name="DoctorDetail")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class DoctorDetail : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new DoctorDetail object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static DoctorDetail CreateDoctorDetail(global::System.Int32 id)
        {
            DoctorDetail doctorDetail = new DoctorDetail();
            doctorDetail.id = id;
            return doctorDetail;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> docid
        {
            get
            {
                return _docid;
            }
            set
            {
                OndocidChanging(value);
                ReportPropertyChanging("docid");
                _docid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("docid");
                OndocidChanged();
            }
        }
        private Nullable<global::System.Int32> _docid;
        partial void OndocidChanging(Nullable<global::System.Int32> value);
        partial void OndocidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String docDescription
        {
            get
            {
                return _docDescription;
            }
            set
            {
                OndocDescriptionChanging(value);
                ReportPropertyChanging("docDescription");
                _docDescription = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("docDescription");
                OndocDescriptionChanged();
            }
        }
        private global::System.String _docDescription;
        partial void OndocDescriptionChanging(global::System.String value);
        partial void OndocDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String fbaccount
        {
            get
            {
                return _fbaccount;
            }
            set
            {
                OnfbaccountChanging(value);
                ReportPropertyChanging("fbaccount");
                _fbaccount = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("fbaccount");
                OnfbaccountChanged();
            }
        }
        private global::System.String _fbaccount;
        partial void OnfbaccountChanging(global::System.String value);
        partial void OnfbaccountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String googleacc
        {
            get
            {
                return _googleacc;
            }
            set
            {
                OngoogleaccChanging(value);
                ReportPropertyChanging("googleacc");
                _googleacc = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("googleacc");
                OngoogleaccChanged();
            }
        }
        private global::System.String _googleacc;
        partial void OngoogleaccChanging(global::System.String value);
        partial void OngoogleaccChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String twitteracc
        {
            get
            {
                return _twitteracc;
            }
            set
            {
                OntwitteraccChanging(value);
                ReportPropertyChanging("twitteracc");
                _twitteracc = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("twitteracc");
                OntwitteraccChanged();
            }
        }
        private global::System.String _twitteracc;
        partial void OntwitteraccChanging(global::System.String value);
        partial void OntwitteraccChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String linkdn
        {
            get
            {
                return _linkdn;
            }
            set
            {
                OnlinkdnChanging(value);
                ReportPropertyChanging("linkdn");
                _linkdn = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("linkdn");
                OnlinkdnChanged();
            }
        }
        private global::System.String _linkdn;
        partial void OnlinkdnChanging(global::System.String value);
        partial void OnlinkdnChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IsDeleted
        {
            get
            {
                return _IsDeleted;
            }
            set
            {
                OnIsDeletedChanging(value);
                ReportPropertyChanging("IsDeleted");
                _IsDeleted = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsDeleted");
                OnIsDeletedChanged();
            }
        }
        private Nullable<global::System.Int32> _IsDeleted;
        partial void OnIsDeletedChanging(Nullable<global::System.Int32> value);
        partial void OnIsDeletedChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CareForYouModel", Name="HomeContent")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class HomeContent : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new HomeContent object.
        /// </summary>
        /// <param name="homeID">Initial value of the HomeID property.</param>
        public static HomeContent CreateHomeContent(global::System.Int32 homeID)
        {
            HomeContent homeContent = new HomeContent();
            homeContent.HomeID = homeID;
            return homeContent;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 HomeID
        {
            get
            {
                return _HomeID;
            }
            set
            {
                if (_HomeID != value)
                {
                    OnHomeIDChanging(value);
                    ReportPropertyChanging("HomeID");
                    _HomeID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("HomeID");
                    OnHomeIDChanged();
                }
            }
        }
        private global::System.Int32 _HomeID;
        partial void OnHomeIDChanging(global::System.Int32 value);
        partial void OnHomeIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String HomeHeader
        {
            get
            {
                return _HomeHeader;
            }
            set
            {
                OnHomeHeaderChanging(value);
                ReportPropertyChanging("HomeHeader");
                _HomeHeader = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("HomeHeader");
                OnHomeHeaderChanged();
            }
        }
        private global::System.String _HomeHeader;
        partial void OnHomeHeaderChanging(global::System.String value);
        partial void OnHomeHeaderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String HomeImage
        {
            get
            {
                return _HomeImage;
            }
            set
            {
                OnHomeImageChanging(value);
                ReportPropertyChanging("HomeImage");
                _HomeImage = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("HomeImage");
                OnHomeImageChanged();
            }
        }
        private global::System.String _HomeImage;
        partial void OnHomeImageChanging(global::System.String value);
        partial void OnHomeImageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String HomeText
        {
            get
            {
                return _HomeText;
            }
            set
            {
                OnHomeTextChanging(value);
                ReportPropertyChanging("HomeText");
                _HomeText = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("HomeText");
                OnHomeTextChanged();
            }
        }
        private global::System.String _HomeText;
        partial void OnHomeTextChanging(global::System.String value);
        partial void OnHomeTextChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String HomeEmail
        {
            get
            {
                return _HomeEmail;
            }
            set
            {
                OnHomeEmailChanging(value);
                ReportPropertyChanging("HomeEmail");
                _HomeEmail = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("HomeEmail");
                OnHomeEmailChanged();
            }
        }
        private global::System.String _HomeEmail;
        partial void OnHomeEmailChanging(global::System.String value);
        partial void OnHomeEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsDeleted
        {
            get
            {
                return _IsDeleted;
            }
            set
            {
                OnIsDeletedChanging(value);
                ReportPropertyChanging("IsDeleted");
                _IsDeleted = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsDeleted");
                OnIsDeletedChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsDeleted;
        partial void OnIsDeletedChanging(Nullable<global::System.Boolean> value);
        partial void OnIsDeletedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CreatedDate
        {
            get
            {
                return _CreatedDate;
            }
            set
            {
                OnCreatedDateChanging(value);
                ReportPropertyChanging("CreatedDate");
                _CreatedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatedDate");
                OnCreatedDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _CreatedDate;
        partial void OnCreatedDateChanging(Nullable<global::System.DateTime> value);
        partial void OnCreatedDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String HomeUrl
        {
            get
            {
                return _HomeUrl;
            }
            set
            {
                OnHomeUrlChanging(value);
                ReportPropertyChanging("HomeUrl");
                _HomeUrl = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("HomeUrl");
                OnHomeUrlChanged();
            }
        }
        private global::System.String _HomeUrl;
        partial void OnHomeUrlChanging(global::System.String value);
        partial void OnHomeUrlChanged();

        #endregion
    
    }

    #endregion
    
}
